/**
 * Next
 */
import React from 'react';
import Head from 'next/head';

/**
 * Redux
 */
import { useSelector } from 'react-redux';
import { wrapper } from '@/Products/Driver/Store/main';
import { fetchNewsFeed, selectNewsFeed } from '@/Products/Driver/Store/newsfeed.slice';

const Home: Next.NextPage = () => {
  const content = useSelector(selectNewsFeed());

  if (!content) {
    return <div>RENDERED WITHOUT CONTENT FROM STORE!!!???</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h3>state</h3>
        <pre>
          id: {content[0].id}, title: {content[0].title}, url: {content[0].url}
        </pre>
      </div>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps((store) => async () => {
  await store.dispatch(fetchNewsFeed());

  return {
    props: {},
  };
});

export default Home;
