/**
 * Next
 */
import Head from 'next/head';

/**
 * Redux
 */
import { useSelector } from 'react-redux';
import { wrapper } from '@/Products/Driver/Store/main';
import { fetchNewsFeed, selectNewsFeed } from '@/Products/Driver/Store/newsfeed.slice';

const Home: Next.NextPage = () => {
  const content = useSelector(selectNewsFeed());

  if (!content) {
    return <div>RENDERED WITHOUT CONTENT FROM STORE!!!???</div>;
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <p className="text-4xl">Welcome to Nextjs</p>
    </>
  );
};

export const getServerSideProps = wrapper.getServerSideProps((store) => async () => {
  await store.dispatch(fetchNewsFeed());

  return {
    props: {},
  };
});

export default Home;
